INSERT INTO `test_club`.`countryinfo` (`CountryName`, `CityName`, `Population`, `isCapital`) VALUES ('United Kingdom', 'London', 8136000, 1);
INSERT INTO `test_club`.`countryinfo` (`CountryName`, `CityName`, `Population`, `isCapital`) VALUES ('Spain', 'Madrid', 3166000, 1);
INSERT INTO `test_club`.`countryinfo` (`CountryName`, `CityName`, `Population`, `isCapital`) VALUES ('South Korea', 'Daegu', 2455000, 0);
INSERT INTO `test_club`.`countryinfo` (`CountryName`, `CityName`, `Population`, `isCapital`) VALUES ('China', 'Chaozhou', 2669000, 0);
INSERT INTO `test_club`.`countryinfo` (`CountryName`, `CityName`, `Population`, `isCapital`) VALUES ('Vietnam', 'Ho Chi Minh City', 8611000, 0);
INSERT INTO `test_club`.`countryinfo` (`CountryName`, `CityName`, `Population`, `isCapital`) VALUES ('South Korea', 'Busan', 3400000, 0);
INSERT INTO `test_club`.`countryinfo` (`CountryName`, `CityName`, `Population`, `isCapital`) VALUES ('Taiwan', 'Taichung', 2792000, 0);
INSERT INTO `test_club`.`countryinfo` (`CountryName`, `CityName`, `Population`, `isCapital`) VALUES ('India', 'Kolkata', 4497000, 0);
INSERT INTO `test_club`.`countryinfo` (`CountryName`, `CityName`, `Population`, `isCapital`) VALUES ('Poland', 'Warsaw', 1735000, 1);
INSERT INTO `test_club`.`countryinfo` (`CountryName`, `CityName`, `Population`, `isCapital`) VALUES ('China', 'Foshan', 7197000, 0);
INSERT INTO `test_club`.`countryinfo` (`CountryName`, `CityName`, `Population`, `isCapital`) VALUES ('Chile', 'Santiago', 5150000, 1);
INSERT INTO `test_club`.`countryinfo` (`CountryName`, `CityName`, `Population`, `isCapital`) VALUES ('Zimbabwe', 'Harare', 1485000, 1);
INSERT INTO `test_club`.`countryinfo` (`CountryName`, `CityName`, `Population`, `isCapital`) VALUES ('Japan', 'Kawasaki', 1475000, 0);
INSERT INTO `test_club`.`countryinfo` (`CountryName`, `CityName`, `Population`, `isCapital`) VALUES ('China', 'Beijing', 21710000, 1);
INSERT INTO `test_club`.`countryinfo` (`CountryName`, `CityName`, `Population`, `isCapital`) VALUES ('China', 'Zunyi', 1095000, 0);
INSERT INTO `test_club`.`countryinfo` (`CountryName`, `CityName`, `Population`, `isCapital`) VALUES ('Iran', 'Ahvaz', 1112000, 0);
INSERT INTO `test_club`.`countryinfo` (`CountryName`, `CityName`, `Population`, `isCapital`) VALUES ('Iraq', 'Baghdad', 7665000, 1);
INSERT INTO `test_club`.`countryinfo` (`CountryName`, `CityName`, `Population`, `isCapital`) VALUES ('India', 'Bhopal', 1798000, 0);
INSERT INTO `test_club`.`countryinfo` (`CountryName`, `CityName`, `Population`, `isCapital`) VALUES ('China', 'Changchun', 7665000, 0);
INSERT INTO `test_club`.`countryinfo` (`CountryName`, `CityName`, `Population`, `isCapital`) VALUES ('Tanzania', 'Dar es Salaam', 454300, 1);
INSERT INTO `test_club`.`countryinfo` (`CountryName`, `CityName`, `Population`, `isCapital`) VALUES ('Turkey', 'Ankara', 5464000, 1);
INSERT INTO `test_club`.`countryinfo` (`CountryName`, `CityName`, `Population`, `isCapital`) VALUES ('Italy', 'Milan', 1300000, 0);
INSERT INTO `test_club`.`countryinfo` (`CountryName`, `CityName`, `Population`, `isCapital`) VALUES ('Nigeria', 'Lagos', 2400000, 1);
INSERT INTO `test_club`.`countryinfo` (`CountryName`, `CityName`, `Population`, `isCapital`) VALUES ('United States', 'San Diego', 540000, 0);
INSERT INTO `test_club`.`countryinfo` (`CountryName`, `CityName`, `Population`, `isCapital`) VALUES ('Ghana', 'Accra', 3454000, 0);
INSERT INTO `test_club`.`countryinfo` (`CountryName`, `CityName`, `Population`, `isCapital`) VALUES ('China', 'Harbin', 1234000, 0);
INSERT INTO `test_club`.`countryinfo` (`CountryName`, `CityName`, `Population`, `isCapital`) VALUES ('Canada', 'Montreal', 675800, 0);
INSERT INTO `test_club`.`countryinfo` (`CountryName`, `CityName`, `Population`, `isCapital`) VALUES ('Ukraine', 'Kyiv', 2804000, 1);
INSERT INTO `test_club`.`countryinfo` (`CountryName`, `CityName`, `Population`, `isCapital`) VALUES ('Ukraine', 'Truskavets', 29500, 0);
INSERT INTO `test_club`.`countryinfo` (`CountryName`, `CityName`, `Population`, `isCapital`) VALUES ('Ukraine', 'Ovruch', 16600, 0);